Increase timeout to 10s

diff --git a/visit-ebay b/visit-ebay
--- a/visit-ebay
+++ b/visit-ebay
@@ -13,8 +13,13 @@ visit_auction() {
 
   echo "=> $url @ $proxy"
   # echo curl --connect-timeout 3 --proxy "$proxy" "$url" --silent
-  curl --connect-timeout 3 --proxy "$proxy" "$url" --silent 2>&1 >/dev/null
-  echo "  - visited"
+  curl --connect-timeout 10 --proxy "$proxy" "$url" --silent 2>&1 >/dev/null
+
+  if [ "$?" = "0" ]; then
+    echo "  - visited"
+  else
+    echo "  - failed"
+  fi
 }
 
 
