Debug

diff --git a/visit-ebay b/visit-ebay
--- a/visit-ebay
+++ b/visit-ebay
@@ -11,21 +11,29 @@ urls_file=${1:-./urls_file}
 proxies_file=${2:-./proxies_file}
 timeout=30
 
+curl_with_proxy() {
+  if [ -z "$DEBUG" ]; then
+    timeout $timeout curl --silent --proxy "$2" "$1" 2>&1 >/dev/null
+  else
+    timeout $timeout curl --proxy "$2" "$1"
+  fi
+}
+
 visit_auction() {
   url="$1"
   proxy="$(sort --random-sort "$proxies_file" | head -1)"
 
-  echo " => $url @ $proxy"
-  timeout $timeout curl --silent --proxy "$proxy" "$url" 2>&1 >/dev/null
+  # echo " => $url via $proxy"
+  curl_with_proxy "$url" "$proxy"
 
-  if [ "$?" = "0" ]; then
-    echo "    [ok] $url @ $proxy"
-  else
-    echo "    [fail] $url @ $proxy"
-  fi
+  # if [ "$?" = "0" ]; then
+  #   echo "    [ok] $url"
+  # else
+  #   echo "    [fail] $url"
+  # fi
 }
 
-for url in $(sort --unique $urls_file | sort --random-sort); do
+for url in $(sort --unique --random-sort $urls_file); do
   visit_auction "$url" &
 done
 
